import os
import shutil
import uuid
from argparse import Namespace
from fastapi import FastAPI, File, UploadFile, Form
from fastapi.responses import FileResponse
from line_extract import refine_scribble, predict_line
from fastapi.middleware.cors import CORSMiddleware
import cv2

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 一時ファイルの保存ディレクトリ
os.makedirs("temp", exist_ok=True)

def save_file(upload_file: UploadFile, destination: str):
    """アップロードされたファイルを指定したパスに保存する"""
    with open(destination, "wb") as f:
        shutil.copyfileobj(upload_file.file, f)

@app.post("/api/refine_scribble")
async def api_refine_scribble(
    image: UploadFile = File(...),
    scribble: UploadFile = File(...),
    use_clahe: bool = Form(False),
    clahe_clip: float = Form(2.0),
    clahe_grid: int = Form(8)
):
    req_id = str(uuid.uuid4())
    img_path = f"temp/{req_id}_img.png"
    scr_path = f"temp/{req_id}_scr.png"
    
    save_file(image, img_path)
    save_file(scribble, scr_path)
    
    refined_scr_u8 = refine_scribble(img_path, scr_path, use_clahe, clahe_clip, clahe_grid)

    refined_scr_path = f"temp/{req_id}_scr_refined.png"
    cv2.imwrite(refined_scr_path, refined_scr_u8)

    if os.path.exists(refined_scr_path):
        return FileResponse(refined_scr_path, media_type="image/png")
    else:
        return {"error": "Output not generated by line_extract.py"}

@app.post("/api/predict_line")
async def api_predict_line(
    image: UploadFile = File(...),
    scribble: UploadFile = File(...),
    refined_scribble: UploadFile = File(...),
    lr: float = Form(1e-3),
    iters: int = Form(1000),
    device: str = Form("cuda")
):

    req_id = str(uuid.uuid4())
    img_path = f"temp/{req_id}_img.png"
    scr_path = f"temp/{req_id}_scr.png"
    refined_scr_path = f"temp/{req_id}_scr_refined.png"
    
    save_file(image, img_path)
    save_file(scribble, scr_path)
    save_file(refined_scribble, refined_scr_path)
    
    predicted_line = predict_line(img_path, scr_path, refined_scr_path, lr, iters, device)

    line_path = f"temp/{req_id}_line.png"
    cv2.imwrite(line_path, predicted_line)

    if os.path.exists(line_path):
        return FileResponse(line_path, media_type="image/png")
    else:
        return {"error": "Output not generated by line_extract.py"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)